- hosts: admin
  user: root
  vars_files:
    - vars/general.yml
    - vars/network.yml
  roles:
    - prereq
    - java
    - iptables
    - ntp
    - pcc

- hosts: all
  user: root
  roles:
    - container-executor