---
- name: copy jdk
  copy: src=jdk-{{ java_version }}-linux-x64.rpm dest=/tmp/jdk-{{ java_version }}-linux-x64.rpm mode=0644 force=no
  register: jdk_copied

- name: install jdk
  yum: name=/tmp/jdk-{{ java_version }}-linux-x64.rpm state=present
  register: jdk_installed
  when: jdk_copied|changed

- name: select default java
  command: alternatives --install /usr/bin/java java /usr/java/latest/bin/java 200000
  when: jdk_installed|changed

- name: select default jar command
  command: alternatives --install /usr/bin/javaws javaws /usr/java/latest/bin/javaws 200000
  when: jdk_installed|changed

- name: add JAVA_HOME to user profile
  copy: src=java.sh dest=/etc/profile.d/java.sh
  when: jdk_installed|changed